name: Build, Release y Cerrar Milestone

on:
  push:
    branches:
      - '#3-release-notas-cobertura'

permissions:
  contents: write
  issues: write

env:
  JAR_NAME_PREFIX: "demo"
  FOLDER_NAME: "."

jobs:
  build_and_upload_artifacts:
    name: Build y subir artifacts
    runs-on: ubuntu-latest

    outputs:
      TAG_RELEASE: ${{ steps.extract-tag.outputs.TAG_RELEASE }}
      MILESTONE_NAME: ${{ steps.milestone.outputs.MILESTONE_NAME }}
      MILESTONE_ID: ${{ steps.milestone.outputs.MILESTONE_ID }}
      TEST_COVERAGE: ${{ steps.coverage.outputs.TEST_COVERAGE }}
      TEST_COUNT: ${{ steps.coverage.outputs.TEST_COUNT }}

    steps:
      - name: Instalar xmllint (libxml2-utils)
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Checkout al repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 21 Zulu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Extraer tag y versión
        id: extract-tag
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          echo "Release del tag: $TAG_NAME"
          echo "TAG_RELEASE=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Obtener milestone correspondiente
        id: milestone
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Buscando milestone para versión: $VERSION"

          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  "https://api.github.com/repos/${{ github.repository }}/milestones?state=open")

          MILESTONE_TITLE=$(echo "$RESPONSE" | jq -r --arg v "$VERSION" '.[] | select(.title | startswith($v)) | .title')
          MILESTONE_ID=$(echo "$RESPONSE" | jq -r --arg v "$VERSION" '.[] | select(.title | startswith($v)) | .number')

          if [ -z "$MILESTONE_TITLE" ] || [ "$MILESTONE_TITLE" = "null" ]; then
            echo "⚠️ Milestone no encontrada para versión $VERSION"
            MILESTONE_TITLE="$TAG_NAME"
            MILESTONE_ID=""
          fi

          echo "🎯 Milestone detectada: $MILESTONE_TITLE (ID: $MILESTONE_ID)"
          echo "MILESTONE_NAME=$MILESTONE_TITLE" >> "$GITHUB_OUTPUT"
          echo "MILESTONE_ID=$MILESTONE_ID" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          mvn clean verify
          JAR_FILE=$(ls target/*.jar | head -n 1)
          FINAL_JAR="target/${{ env.JAR_NAME_PREFIX }}-${{ steps.extract-tag.outputs.TAG_RELEASE }}.jar"
          mv "$JAR_FILE" "$FINAL_JAR"
        working-directory: ${{ env.FOLDER_NAME }}

      - name: Extraer cobertura de tests
        id: coverage
        run: |
          XML_FILE="${{ env.FOLDER_NAME }}/target/site/jacoco/jacoco.xml"
          
          if [[ -f "$XML_FILE" ]]; then
            COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" "$XML_FILE")
            MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" "$XML_FILE")
            TOTAL=$((COVERAGE + MISSED))
            PERCENT=$((100 * COVERAGE / TOTAL))
            echo "Cobertura: $PERCENT%"
            echo "TEST_COVERAGE=$PERCENT" >> "$GITHUB_OUTPUT"
          else
            echo "⚠️ Archivo de cobertura no encontrado"
            echo "TEST_COVERAGE=N/A" >> "$GITHUB_OUTPUT"
          fi

          TEST_REPORT="${{ env.FOLDER_NAME }}/target/surefire-reports"
          if [[ -d "$TEST_REPORT" ]]; then
            TEST_COUNT=$(grep -hEo 'Tests run: [0-9]+' "$TEST_REPORT"/*.txt | awk '{s+=$3} END {print s}')
            if [ -z "$TEST_COUNT" ]; then
              TEST_COUNT=0
            fi
          else
            TEST_COUNT="N/A"
          fi
          echo "TEST_COUNT=$TEST_COUNT" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JAR_NAME_PREFIX }}-${{ steps.extract-tag.outputs.TAG_RELEASE }}.jar
          path: ${{ env.FOLDER_NAME }}/target/${{ env.JAR_NAME_PREFIX }}-${{ steps.extract-tag.outputs.TAG_RELEASE }}.jar
          retention-days: 1

  create_release:
    name: Crear release y subir assets
    runs-on: ubuntu-latest
    needs: build_and_upload_artifacts

    steps:
      - name: Descargar JAR
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.JAR_NAME_PREFIX }}-${{ needs.build_and_upload_artifacts.outputs.TAG_RELEASE }}.jar
          path: ./

      - name: Crear Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build_and_upload_artifacts.outputs.TAG_RELEASE }}
          name: ${{ needs.build_and_upload_artifacts.outputs.MILESTONE_NAME }}
          generate_release_notes: true
          append_body: true
          files: |
            ${{ env.JAR_NAME_PREFIX }}-${{ needs.build_and_upload_artifacts.outputs.TAG_RELEASE }}.jar

      - name: Añadir cobertura de tests a la release
        run: |
          TAG="${{ needs.build_and_upload_artifacts.outputs.TAG_RELEASE }}"
          COVERAGE="${{ needs.build_and_upload_artifacts.outputs.TEST_COVERAGE }}"
          TESTS="${{ needs.build_and_upload_artifacts.outputs.TEST_COUNT }}"

          RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG")

          RELEASE_ID=$(echo "$RELEASE" | jq -r .id)
          CURRENT_BODY=$(echo "$RELEASE" | jq -r .body)

          NEW_BODY="$CURRENT_BODY
          ---
          **Cantidad de test ejecutados:** $TESTS"
          **Porcentaje de cobertura:** $COVERAGE%"

          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$(jq -n --arg body "$NEW_BODY" '{body: $body}')" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"


  close_milestone:
    name: Cerrar Milestone
    runs-on: ubuntu-latest
    needs: build_and_upload_artifacts

    if: needs.build_and_upload_artifacts.outputs.MILESTONE_ID != ''

    steps:
      - name: Cerrar milestone
        run: |
          MILESTONE_ID="${{ needs.build_and_upload_artifacts.outputs.MILESTONE_ID }}"
          echo "🔒 Cerrando milestone con ID: $MILESTONE_ID..."

          RESPONSE=$(curl -s -X PATCH             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"             -H "Accept: application/vnd.github.v3+json"             -d '{"state":"closed"}'             "https://api.github.com/repos/${{ github.repository }}/milestones/$MILESTONE_ID")

          if ! echo "$RESPONSE" | jq -e . > /dev/null; then
            echo "❌ Falló el cierre del milestone"
            echo "$RESPONSE"
            exit 1
          fi

          echo "🎉 Milestone cerrado exitosamente."
